name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  Testing:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3  # Cambiamos a una imagen con PHP 8.3 y PostgreSQL compatible
      options: --user 1001

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: app_tests
          POSTGRES_HOST: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: app_tests
      DB_USERNAME: default
      DB_PASSWORD: secret

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
        working-directory: ./backend

      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        working-directory: ./backend

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install composer dependencies
        run: |
          composer install --no-scripts
        working-directory: ./backend

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
        working-directory: ./backend

      - name: Run Testsuite
        run: php artisan test
        working-directory: ./backend
